### ISSUE TITLE
Starting with Perl 5.14, "unshift" can take a scalar EXPR, which must hold a reference to an unblessed array.

### ISSUE THREAD

**Issue by apocalypse** [neilb/Perl-MinimumVersion#1]
Hello,

  I've been a happy user of your module for a while! However, when I added code that used the new unshift feature, my dist blew up on cpantesters because P::MV identified it as 5.006! The code is: 

https://github.com/apocalypse/perl-dist-zilla-plugin-authority/blob/master/lib/Dist/Zilla/Plugin/Authority.pm#L239 which was

unshift $block->{children},
PPI::Token::Whitespace->new("\n"),
$self->_make_authority( $package ),
PPI::Token::Whitespace->new("\n");

I've also filed a corresponding ticket against PMV::Fast because it also failed, returning 5.008 too.

https://github.com/tokuhirom/Perl-MinimumVersion-Fast/issues/8

Thanks again for looking into this!

**Comment by tokuhirom** [comment]
P::MV::Fast was fixed by ISHIGAKI-san.
https://github.com/tokuhirom/Perl-MinimumVersion-Fast/pull/9

**Comment by Grinnz** [comment]
This feature has been removed from perl anyway...
