### ISSUE TITLE
Missing XSLoader detection.

### ISSUE THREAD

**Issue by toddr** [neilb/Perl-MinimumVersion#12]
If use XSLoader is seen, then that makes the minimum version 5.6.0 because according to corelist:

"XSLoader was first released with perl v5.6.0"

**Comment by chorny** [comment]
XSLoader is available on CPAN, cpantesters even have PASS report for 5.004_05

**Comment by toddr** [comment]
Wouldn't that still make it 5.4 then? ¯\_(ツ)_/¯

**Comment by Grinnz** [comment]
After #7, the analyzer will hopefully not care about any pre-5.6 requirements anyway...
