### ISSUE TITLE
perlver should die if the script doesn't compile

### ISSUE THREAD

**Issue by pryrt** [neilb/Perl-MinimumVersion#32]
After reading [this perlmonks post](https://perlmonks.org/?node_id=11155549), I did some investigating, and narrowed it down to 3 separate bugs or feature requests, which I'm raising as three separate issues.

I would think that if the script that you pass to `perlver` doesn't compile, it wouldn't try to tell you what version is required.  For example, the code:

**code: `doesnt_compile.pl`**
```pl
#!/usr/bin/perl

say "Hello";
```

Running `perlver doesnt_compile.pl` yields:
```txt
   ------------------------------------------------
 | file              | explicit | syntax | external |
 | ------------------------------------------------ |
 | doesnt_compile.pl | ~        | ~      | n/a      |
 | ------------------------------------------------ |
 | Minimum explicit version : ~                             |
 | Minimum syntax version   : ~                             |
 | Minimum version of perl  : v5.4.0 (default)              |
   ------------------------------------------------
```

I would expect this to die with some sort of error message.  Maybe "cannot compile 'doesnt_compile.pl' so cannot determine minimum perl version required"

(If I add the `use feature qw(say);`, it will compile, and `perlver` correctly tells me it needs v5.10.0.)

(verified with `perlver` v1.40 on Perl 5.32)

**Comment by Grinnz** [comment]
perlver is a static analysis tool, and thus determining whether your code compiles is, in my opinion, beyond its scope.

**Comment by pryrt** [comment]
The script it is analyzing is calling `say`: either it needs to tell you that it requires 5.10, or it needs to admit it cannot figure out the minimum perl required.  It does neither of these.

**Comment by Grinnz** [comment]
There are many ways for 'say' to be valid syntax that do not require 5.10, the most common being a declared `sub say`.
